PINECONE_API_KEY = '09363b67-7ea8-43a6-b6d2-2990d0ebbee6'
QUIZ_CSV ="https://docs.google.com/spreadsheets/d/e/2PACX-1vS1YbfywK6xjrr14JEcjTfPyVSBroouwCBkxdYNMObcIwPk8rdJwWlHCgohoso3t01DOpPeQ20JSkAG/pub?gid=0&single=true&output=csv"